/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.MotoristasDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Motoristas;

/**
 *
 * @author PICHAU
 */
public class MotoristasGUI extends javax.swing.JFrame {

    /**
     * Creates new form MotoristasGUI
     */
    public MotoristasGUI() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("Cadastro de Motoristas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdMotoristas = new javax.swing.JTextField();
        txtNomeMotoristas = new javax.swing.JTextField();
        txtNascimentoMotoristas = new javax.swing.JTextField();
        txtCnhMotoristas = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMotoristas = new javax.swing.JMenu();
        jSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CADASTRO DE MOTORISTAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nascimento:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("CNH:");

        txtNomeMotoristas.setEnabled(false);

        txtNascimentoMotoristas.setEnabled(false);

        txtCnhMotoristas.setEnabled(false);

        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnLimpar.setText("LIMPAR");
        btnLimpar.setEnabled(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSalvar.setText("SALVAR");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.setEnabled(false);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(55, 55, 55)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtIdMotoristas)
                                .addComponent(txtNomeMotoristas, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNascimentoMotoristas)
                                .addComponent(txtCnhMotoristas))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPesquisar)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnAtualizar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar)))))
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdMotoristas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeMotoristas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNascimentoMotoristas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCnhMotoristas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnNovo)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAtualizar))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jMotoristas.setText("Motoristas");
        jMotoristas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMotoristasMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMotoristas);

        jSair.setText("Sair");
        jSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMotoristasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMotoristasMouseClicked
        txtIdMotoristas.setText("");
        txtNomeMotoristas.setText("");
        txtNascimentoMotoristas.setText("");
        txtCnhMotoristas.setText("");
        
        txtIdMotoristas.setEnabled(true);
        txtNomeMotoristas.setEnabled(false);
        txtNascimentoMotoristas.setEnabled(false);
        txtCnhMotoristas.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnLimpar.setEnabled(false);
        btnPesquisar.setEnabled(true);
        btnNovo.setEnabled(true);
    }//GEN-LAST:event_jMotoristasMouseClicked

    private void jSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSairMouseClicked
        int opcao = JOptionPane.showConfirmDialog(null, 
                "Deseja realmente sair?", "Aviso",JOptionPane.YES_NO_OPTION);
        if (opcao ==0){
            System.exit(0);
            
        }
        else{
            
        }
        
    }//GEN-LAST:event_jSairMouseClicked

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
         txtNomeMotoristas.setEnabled(true);
         txtNascimentoMotoristas.setEnabled(true);
         txtCnhMotoristas.setEnabled(true);      
         btnLimpar.setEnabled(true);
         btnExcluir.setEnabled(true);
         btnAtualizar.setEnabled(true);
         
        if (txtIdMotoristas.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Digite o ID do Motorista");
            
            
            
        } else {
            
            
            Motoristas motoristas = new Motoristas();
            motoristas.setId_motoristas(Integer.parseInt(txtIdMotoristas.getText()));
            
            MotoristasDAO dao = new MotoristasDAO();
            motoristas = dao.consultar(motoristas);
            
            if(motoristas != null){
                
                txtNomeMotoristas.setText(motoristas.getNome_motoristas());
                txtNascimentoMotoristas.setText(motoristas.getNascimento_motoristas());
                txtCnhMotoristas.setText(motoristas.getCnh_motoristas());
                
                
                
                
            }
            
            else{
                
               JOptionPane.showMessageDialog(null, "ID Inválido");
            
                
            }
            
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtNomeMotoristas.setEnabled(true);
        txtNascimentoMotoristas.setEnabled(true);
        txtCnhMotoristas.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnLimpar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnAtualizar.setEnabled(true);
        btnPesquisar.setEnabled(false);
        
        txtIdMotoristas.setEnabled(false);
        txtIdMotoristas.setText("");
        txtNomeMotoristas.setText("");
        txtNascimentoMotoristas.setText("");
        txtCnhMotoristas.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNomeMotoristas.setText("");
        txtNascimentoMotoristas.setText("");
        txtCnhMotoristas.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Motoristas motoristas = new Motoristas();
        motoristas.setNome_motoristas(txtNomeMotoristas.getText());
        motoristas.setNascimento_motoristas(txtNascimentoMotoristas.getText());
        motoristas.setCnh_motoristas(txtCnhMotoristas.getText());
        
        if (txtNomeMotoristas.getText().isEmpty() || 
            txtNascimentoMotoristas.getText().isEmpty()  || 
            txtCnhMotoristas.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
       
            
        }
        else{
            
            MotoristasDAO dao = new MotoristasDAO();
            dao.inserir(motoristas);
            
             JOptionPane.showMessageDialog(null, "Motorista "+ txtNomeMotoristas.getText()
                    +" foi inserido com sucesso"); 
            
        }
        
          txtNomeMotoristas.setText("");
          txtNascimentoMotoristas.setText("");
          txtCnhMotoristas.setText("");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(txtIdMotoristas.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Digite o ID do Motorista");
            
        }
        
        else{
            
            try {
                
              Class.forName("com.mysql.cj.jdbc.Driver");
               
               Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/av5?useTimezone=true&serverTimezone=UTC","root","");
               
               java.sql.Statement st = conn.createStatement();
               st.executeUpdate("delete from motoristas where id_motoristas = ?  + this.txtIdMostoristas.getText()");
               JOptionPane.showMessageDialog(rootPane, "Motorista excluído com sucesso!");
              
                
            } catch (ClassNotFoundException e) {
               JOptionPane.showMessageDialog(rootPane, e);  
                
            } catch (SQLException ex) {
                Logger.getLogger(MotoristasGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
             
             txtNomeMotoristas.setText("");
             txtNascimentoMotoristas.setText("");
             txtCnhMotoristas.setText("");
        
        } 
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
         Motoristas medicos = new Motoristas();
        medicos.setNome_motoristas(txtNomeMotoristas.getText());
        medicos.setNascimento_motoristas(txtNascimentoMotoristas.getText());
        medicos.setCnh_motoristas(txtCnhMotoristas.getText());
       
        
       
           JOptionPane.showMessageDialog(null, "Motorista "+ txtNomeMotoristas.getText()
                    +" foi atualizado com sucesso"); 
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotoristasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotoristasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotoristasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotoristasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MotoristasGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMotoristas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jSair;
    private javax.swing.JTextField txtCnhMotoristas;
    private javax.swing.JTextField txtIdMotoristas;
    private javax.swing.JTextField txtNascimentoMotoristas;
    private javax.swing.JTextField txtNomeMotoristas;
    // End of variables declaration//GEN-END:variables
}
